/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DrawLotteryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_NUMBER"
      | "MIN_NUMBER"
      | "SHAKE_FEE"
      | "checkWin"
      | "closeRound"
      | "currentRound"
      | "drawWinningNumber"
      | "getParticipantCount"
      | "getParticipants"
      | "getTotalShakes"
      | "getUserNumber"
      | "getUserShakeCount"
      | "getWinningNumber"
      | "isRoundDrawn"
      | "isRoundOpen"
      | "owner"
      | "protocolId"
      | "shake"
      | "startNewRound"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DrawCompleted"
      | "NewRoundStarted"
      | "NumberShaken"
      | "RoundClosed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_NUMBER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_NUMBER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "SHAKE_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkWin",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "drawWinningNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipantCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalShakes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserNumber",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserShakeCount",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinningNumber",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRoundDrawn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRoundOpen",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "shake",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startNewRound",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "MAX_NUMBER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_NUMBER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SHAKE_FEE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkWin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "closeRound", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "drawWinningNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipantCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalShakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserShakeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWinningNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRoundDrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRoundOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startNewRound",
    data: BytesLike
  ): Result;
}

export namespace DrawCompletedEvent {
  export type InputTuple = [round: BigNumberish, winningNumber: BigNumberish];
  export type OutputTuple = [round: bigint, winningNumber: bigint];
  export interface OutputObject {
    round: bigint;
    winningNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewRoundStartedEvent {
  export type InputTuple = [round: BigNumberish];
  export type OutputTuple = [round: bigint];
  export interface OutputObject {
    round: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NumberShakenEvent {
  export type InputTuple = [
    user: AddressLike,
    round: BigNumberish,
    shakeIndex: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    round: bigint,
    shakeIndex: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    round: bigint;
    shakeIndex: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoundClosedEvent {
  export type InputTuple = [round: BigNumberish];
  export type OutputTuple = [round: bigint];
  export interface OutputObject {
    round: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DrawLottery extends BaseContract {
  connect(runner?: ContractRunner | null): DrawLottery;
  waitForDeployment(): Promise<this>;

  interface: DrawLotteryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_NUMBER: TypedContractMethod<[], [bigint], "view">;

  MIN_NUMBER: TypedContractMethod<[], [bigint], "view">;

  SHAKE_FEE: TypedContractMethod<[], [bigint], "view">;

  checkWin: TypedContractMethod<
    [round: BigNumberish, shakeIndex: BigNumberish],
    [string],
    "nonpayable"
  >;

  closeRound: TypedContractMethod<[], [void], "nonpayable">;

  currentRound: TypedContractMethod<[], [bigint], "view">;

  drawWinningNumber: TypedContractMethod<[], [void], "nonpayable">;

  getParticipantCount: TypedContractMethod<
    [round: BigNumberish],
    [bigint],
    "view"
  >;

  getParticipants: TypedContractMethod<
    [round: BigNumberish],
    [string[]],
    "view"
  >;

  getTotalShakes: TypedContractMethod<[round: BigNumberish], [bigint], "view">;

  getUserNumber: TypedContractMethod<
    [round: BigNumberish, user: AddressLike, shakeIndex: BigNumberish],
    [string],
    "view"
  >;

  getUserShakeCount: TypedContractMethod<
    [round: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  getWinningNumber: TypedContractMethod<
    [round: BigNumberish],
    [bigint],
    "view"
  >;

  isRoundDrawn: TypedContractMethod<[round: BigNumberish], [boolean], "view">;

  isRoundOpen: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  shake: TypedContractMethod<
    [encryptedNumber: BytesLike, inputProof: BytesLike],
    [void],
    "payable"
  >;

  startNewRound: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_NUMBER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_NUMBER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SHAKE_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkWin"
  ): TypedContractMethod<
    [round: BigNumberish, shakeIndex: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "closeRound"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentRound"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "drawWinningNumber"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getParticipantCount"
  ): TypedContractMethod<[round: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getParticipants"
  ): TypedContractMethod<[round: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalShakes"
  ): TypedContractMethod<[round: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserNumber"
  ): TypedContractMethod<
    [round: BigNumberish, user: AddressLike, shakeIndex: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserShakeCount"
  ): TypedContractMethod<
    [round: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWinningNumber"
  ): TypedContractMethod<[round: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "isRoundDrawn"
  ): TypedContractMethod<[round: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRoundOpen"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "shake"
  ): TypedContractMethod<
    [encryptedNumber: BytesLike, inputProof: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "startNewRound"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "DrawCompleted"
  ): TypedContractEvent<
    DrawCompletedEvent.InputTuple,
    DrawCompletedEvent.OutputTuple,
    DrawCompletedEvent.OutputObject
  >;
  getEvent(
    key: "NewRoundStarted"
  ): TypedContractEvent<
    NewRoundStartedEvent.InputTuple,
    NewRoundStartedEvent.OutputTuple,
    NewRoundStartedEvent.OutputObject
  >;
  getEvent(
    key: "NumberShaken"
  ): TypedContractEvent<
    NumberShakenEvent.InputTuple,
    NumberShakenEvent.OutputTuple,
    NumberShakenEvent.OutputObject
  >;
  getEvent(
    key: "RoundClosed"
  ): TypedContractEvent<
    RoundClosedEvent.InputTuple,
    RoundClosedEvent.OutputTuple,
    RoundClosedEvent.OutputObject
  >;

  filters: {
    "DrawCompleted(uint256,uint32)": TypedContractEvent<
      DrawCompletedEvent.InputTuple,
      DrawCompletedEvent.OutputTuple,
      DrawCompletedEvent.OutputObject
    >;
    DrawCompleted: TypedContractEvent<
      DrawCompletedEvent.InputTuple,
      DrawCompletedEvent.OutputTuple,
      DrawCompletedEvent.OutputObject
    >;

    "NewRoundStarted(uint256)": TypedContractEvent<
      NewRoundStartedEvent.InputTuple,
      NewRoundStartedEvent.OutputTuple,
      NewRoundStartedEvent.OutputObject
    >;
    NewRoundStarted: TypedContractEvent<
      NewRoundStartedEvent.InputTuple,
      NewRoundStartedEvent.OutputTuple,
      NewRoundStartedEvent.OutputObject
    >;

    "NumberShaken(address,uint256,uint256,uint256)": TypedContractEvent<
      NumberShakenEvent.InputTuple,
      NumberShakenEvent.OutputTuple,
      NumberShakenEvent.OutputObject
    >;
    NumberShaken: TypedContractEvent<
      NumberShakenEvent.InputTuple,
      NumberShakenEvent.OutputTuple,
      NumberShakenEvent.OutputObject
    >;

    "RoundClosed(uint256)": TypedContractEvent<
      RoundClosedEvent.InputTuple,
      RoundClosedEvent.OutputTuple,
      RoundClosedEvent.OutputObject
    >;
    RoundClosed: TypedContractEvent<
      RoundClosedEvent.InputTuple,
      RoundClosedEvent.OutputTuple,
      RoundClosedEvent.OutputObject
    >;
  };
}
